HW4 is completed
leonid-tankov/go-hw pull request #4
Opened 2023-07-20 14:15 UTC by leonid-tankov

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-07-20 15:34 UTC, ityulkanov requested changes
Оставил парочку небольших комментариев, важный один - тот который касается выполнения условия o(1)

2023-07-20 15:34 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +	if item := lru.queue.Back(); item != nil {
вот тут нужно поправить, иначе условие с o(n) не выполняется

2023-07-20 15:34 UTC, ityulkanov commented on hw04_lru_cache/go.mod
> +module github.com/leonid-tankov/hw04_lru_cache
```suggestion
module github.com/leonid-tankov/go-hw/hw04_lru_cache
```

2023-07-20 15:34 UTC, ityulkanov commented on hw04_lru_cache/list.go
> +	if item.Prev == nil {
можно было бы ещё проверку на l > 0 дописать, для того чтобы в случае дальнейшего расширения нашего кеша избежать возможных ошибок

2023-07-20 16:37 UTC, leonid-tankov commented on hw04_lru_cache/cache.go
> +	if item := lru.queue.Back(); item != nil {
а почему не о(1)? ведь в функции clearLast все операции о(1), разве нет?

2023-07-20 16:47 UTC, leonid-tankov commented on hw04_lru_cache/list.go
> +	if item.Prev == nil {
не до конца понял как удаление элемента влияет на расширение

2023-07-21 07:15 UTC, leonid-tankov commented on hw04_lru_cache/list.go
> +	if item.Prev == nil {
или подразумевается проверка длины на равенство 0, чтобы паники избежать?

2023-07-21 10:49 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +	if item := lru.queue.Back(); item != nil {
А, да, точно же. Снимаю комментарий. Показалось.

2023-07-21 10:49 UTC, ityulkanov commented on hw04_lru_cache/list.go
> +	if item.Prev == nil {
Да, не корректно описал, речь о расширении кодовой базы конечно. Проверку на len > 0 чтобы избежать паники, да.

2023-07-21 11:34 UTC, ityulkanov approved these changes

2023-07-21 12:37 UTC, leonid-tankov commented on hw04_lru_cache/list.go
> +	if item.Prev == nil {
Добавил условие

2023-07-21 12:39 UTC, merged