HW7 is completed
leonid-tankov/go-hw pull request #7
Opened 2023-07-20 14:19 UTC by leonid-tankov

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-07-24 13:25 UTC, ityulkanov requested changes

2023-07-24 13:25 UTC, ityulkanov commented on hw07_file_copying/copy.go
> +	BufferSize               = 100
Эту переменную, имхо нет смысла экспортировать, она нам нужна только в одном месте в программе. Ну и по идее было бы правильнее её высчитывать динамически, в зависимости от размера файла

2023-07-24 13:25 UTC, ityulkanov commented on hw07_file_copying/copy.go
> +
рекомендую вам добавить тут же ещё проверки на: 
наличие самого файла по указанному пути (верен ли путь) 
на попытку записи в /root папку - туда нашей утилите писать нет необходимости
на дублирование пути (т.е to == from) можно не только через strings.Equal а и проверять на совпадение пути вроде вот такого ~/Downloads/file.txt  и /home/user/Downloads/file.txt, но это уже в идеале

2023-09-13 09:41 UTC, leonid-tankov commented on hw07_file_copying/copy.go
> +
проверки добавил

2023-09-13 09:41 UTC, leonid-tankov commented on hw07_file_copying/copy.go
> +	BufferSize               = 100
поменял логику

2023-09-13 14:21 UTC, merged